import { ArrowRight, Blocks, CheckCircle2, Clock3, Code2, Network, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import SectionHeader from '../components/SectionHeader'
import StatusDot from '../components/StatusDot'
import { NETWORKS } from '../config/networks'

export default function Mainnet(){const n=NETWORKS.mainnet;return <main>
  <section className="page-hero mainnet-page-hero"><div className="shell page-hero-grid"><div><StatusDot tone="future">PRODUCTION NETWORK · AFTER TESTNET</StatusDot><span className="page-kicker">RABBIT MAINNET · CHAIN ID 928</span><h1>The production network <em>comes after public proof.</em></h1><p>Mainnet is the long-term Rabbit network, but it does not lead the launch sequence. Public Testnet validation comes first.</p><div className="hero-ctas"><Link className="button primary" to="/testnet">Go to Testnet <ArrowRight size={15}/></Link><Link className="button secondary" to="/lcq">Review LCQ</Link></div></div><div className="network-detail-card mainnet-detail"><div className="network-detail-top"><img src="/rabbit-mark.png" alt=""/><div><span>RABBIT MAINNET</span><b>PRODUCTION NETWORK</b></div><StatusDot tone="future">NOT LAUNCHED</StatusDot></div><div className="network-detail-grid"><div><span>CHAIN ID</span><strong>{n.chainId}</strong></div><div><span>HEX</span><strong>{n.chainIdHex}</strong></div><div><span>CONSENSUS</span><strong>LCQ</strong></div><div><span>EXECUTION</span><strong>EVM</strong></div><div><span>ASSET</span><strong>RAB</strong></div><div><span>PHASE</span><strong>POST-TESTNET</strong></div></div></div></div></section>
  <section className="page-section shell"><SectionHeader eyebrow="LAUNCH PRINCIPLE" title="Mainnet should inherit what Testnet proves." text="The production network should open only after the public path has exercised the protocol and the surrounding infrastructure." />
    <div className="gate-grid"><article><span>01</span><Network/><h3>Network operation</h3><p>Independent nodes discover peers, sync, restart and propagate blocks reliably.</p></article><article><span>02</span><Blocks/><h3>Consensus behavior</h3><p>LCQ producer selection, fallback, rewards and recovery behave correctly under public load.</p></article><article><span>03</span><Code2/><h3>Developer surface</h3><p>EVM, JSON-RPC, wallets, explorer and developer tooling are validated on the public network.</p></article><article><span>04</span><ShieldCheck/><h3>Release gates</h3><p>Final binaries, genesis, hashes and launch configuration are deliberately finalized for Mainnet.</p></article></div>
  </section>
  <section className="roadmap-mainnet"><div className="shell"><SectionHeader eyebrow="ROAD TO MAINNET" title="A visible launch sequence." text="The site keeps Mainnet detailed and discoverable without presenting it as live before it exists." />
    <div className="mainnet-timeline"><div className="timeline-item active"><span>1</span><div><small>FIRST</small><h3>Rabbit Testnet</h3><p>Public mining, nodes, wallets, faucet, explorer and applications.</p></div><StatusDot tone="launch">FIRST RELEASE</StatusDot></div><div className="timeline-item"><span>2</span><div><small>HARDEN</small><h3>Public validation</h3><p>Observe, test failure modes, validate operations and complete release gates.</p></div><StatusDot>VALIDATION</StatusDot></div><div className="timeline-item"><span>3</span><div><small>FINALIZE</small><h3>Mainnet release</h3><p>Finalize production genesis, binaries and official infrastructure.</p></div><StatusDot tone="future">AFTER TESTNET</StatusDot></div><div className="timeline-item"><span>4</span><div><small>OPERATE</small><h3>Permissionless Mainnet</h3><p>Chain ID 928 becomes the production Rabbit network.</p></div><Clock3 size={18}/></div></div>
  </div></section>
  <section className="page-section shell"><SectionHeader eyebrow="MAINNET REFERENCE" title="Production identity, already reserved." text="These identifiers give developers a stable target while service endpoints remain inactive until launch." />
    <div className="reference-grid"><div><span>Network</span><b>Rabbit Mainnet</b></div><div><span>Chain ID</span><b>928</b></div><div><span>Native asset</span><b>RAB</b></div><div><span>Consensus</span><b>LCQ</b></div><div><span>Execution</span><b>EVM</b></div><div><span>Public status</span><b>After Testnet</b></div></div>
  </section>
</main>}
