import { ArrowRight, CheckCircle2, Cpu, Download, FileCheck2, HardDrive, MonitorDown, ShieldCheck, TerminalSquare } from 'lucide-react'
import { Link } from 'react-router-dom'
import SectionHeader from '../components/SectionHeader'
import StatusDot from '../components/StatusDot'

const platforms=[
  ['Windows','x86_64','ZIP release',MonitorDown],
  ['Linux / Ubuntu','x86_64','tar.gz release',TerminalSquare],
  ['macOS','ARM64 / x86_64','release track',Cpu]
]

export default function Mining(){return <main>
  <section className="page-hero mining-page-hero"><div className="shell page-hero-grid"><div><StatusDot tone="launch">TESTNET MINING FIRST</StatusDot><span className="page-kicker">PARTICIPATE IN RABBIT</span><h1>Download.<br/>Run.<br/><em>Compete for opportunity.</em></h1><p>Rabbit mining is designed around permissionless participation: run the official client, generate valid work and let LCQ coordinate block-production opportunities.</p><div className="hero-ctas"><a className="button primary" href="#downloads">Release track <ArrowRight size={15}/></a><Link className="button secondary" to="/lcq">How LCQ works</Link></div></div><div className="mining-console"><div className="console-head"><span>rabbit-node</span><StatusDot tone="launch">TESTNET PROFILE</StatusDot></div><pre><code><span>$</span> rabbit --network rabbit-testnet{`\n\n`}<b>✓</b> client initialized{`\n`}<b>✓</b> P2P discovery active{`\n`}<b>✓</b> LCQ consensus loaded{`\n`}<b>✓</b> participant wallet ready{`\n\n`}<em>waiting for public Testnet release_</em></code></pre></div></div></section>
  <section className="page-section shell" id="downloads"><SectionHeader eyebrow="OFFICIAL RELEASES" title="Downloads should be verifiable, not mysterious." text="The website is prepared for platform downloads, release versions, SHA-256 hashes and GitHub release links. Buttons stay disabled until the public binaries are published." />
    <div className="download-grid">{platforms.map(([name,arch,type,Icon])=><article key={name}><Icon size={23}/><span>{arch}</span><h3>{name}</h3><p>{type}</p><div className="download-meta"><small>VERSION</small><b>Pending public release</b><small>SHA-256</small><b>Published with release</b></div><button disabled><Download size={15}/>Coming with Testnet</button></article>)}</div>
  </section>
  <section className="mining-steps-section"><div className="shell"><SectionHeader eyebrow="MINING FLOW" title="A short path from release to participation." />
    <div className="mining-steps"><article><span>01</span><Download/><h3>Download</h3><p>Use the official Rabbit release for your operating system.</p></article><article><span>02</span><FileCheck2/><h3>Verify</h3><p>Compare the release SHA-256 before running the binary.</p></article><article><span>03</span><HardDrive/><h3>Initialize</h3><p>Create a clean Testnet data directory and network configuration.</p></article><article><span>04</span><Cpu/><h3>Participate</h3><p>Connect to P2P, generate valid work and enter the LCQ flow when eligible.</p></article></div>
  </div></section>
  <section className="page-section shell"><div className="operator-split"><div><span>MINER VS NODE</span><h2>Mining and infrastructure are related, but not identical.</h2><p>A miner participates in work and LCQ producer opportunities. A node can also exist to relay, query, index or serve infrastructure without being presented as the same workflow.</p><Link className="text-link" to="/nodes">Read the node operator guide <ArrowRight size={15}/></Link></div><div className="operator-cards"><article><Cpu/><h3>Miner</h3><ul><li>Valid work</li><li>Participant wallet</li><li>LCQ eligibility</li><li>Producer opportunities</li></ul></article><article><TerminalSquare/><h3>Node operator</h3><ul><li>P2P participation</li><li>Chain synchronization</li><li>RPC / infrastructure</li><li>Independent operation</li></ul></article></div></div></section>
  <section className="security-download"><div className="shell"><ShieldCheck size={30}/><div><span>RELEASE SECURITY</span><h2>Never download a miner from a random link.</h2><p>Rabbit releases should be linked from the official GitHub and RabbitChain.org, with hashes published beside the download. The website never needs your seed phrase or private key to install a client.</p></div><a href="https://github.com/rabbitmainnet" target="_blank" rel="noreferrer">Official GitHub <ArrowRight size={15}/></a></div></section>
</main>}
