import { ArrowRight, Database, Globe2, HardDrive, Network, Radio, Server, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import SectionHeader from '../components/SectionHeader'
import StatusDot from '../components/StatusDot'

export default function Nodes(){return <main>
  <section className="page-hero nodes-page-hero"><div className="shell page-hero-grid"><div><StatusDot tone="tech">PERMISSIONLESS P2P</StatusDot><span className="page-kicker">RUN RABBIT INFRASTRUCTURE</span><h1>Independent nodes make the network <em>real.</em></h1><p>Rabbit is designed to propagate peer-to-peer. Official infrastructure is an entry point, not a requirement that every user depend on one operator.</p><div className="hero-ctas"><a className="button primary" href="#roles">Node roles <ArrowRight size={15}/></a><Link className="button secondary" to="/testnet">Testnet hub</Link></div></div><div className="node-map-card"><div className="node-map-top"><span>P2P NETWORK MODEL</span><b>NO SINGLE RPC REQUIRED</b></div><div className="node-map"><div className="node-map-core"><img src="/rabbit-mark.png" alt=""/></div>{['FULL','MINER','RPC','INDEX','FULL','MINER'].map((x,i)=><div key={i} className={`map-node map-node-${i}`}><i/><span>{x}</span></div>)}<svg viewBox="0 0 600 360" preserveAspectRatio="none" aria-hidden="true"><path d="M300 180 L110 85 M300 180 L180 270 M300 180 L480 75 M300 180 L500 250 M110 85 L480 75 M180 270 L500 250"/></svg></div></div></div></section>
  <section className="page-section shell" id="roles"><SectionHeader eyebrow="NODE ROLES" title="Operate Rabbit for the job you need." text="The public documentation will publish exact hardware and port requirements with the Testnet release. The portal already separates roles so operators can find the right path." />
    <div className="node-role-grid"><article><Server/><span>01</span><h3>Full node</h3><p>Sync and verify the chain while participating in P2P propagation.</p></article><article><Radio/><span>02</span><h3>RPC node</h3><p>Expose JSON-RPC for wallets, applications and infrastructure you operate.</p></article><article><Database/><span>03</span><h3>Archive / indexer</h3><p>Retain or index deeper history for explorers, analytics and advanced services.</p></article><article><Network/><span>04</span><h3>Mining node</h3><p>Run the network client with a participant wallet and mining workflow.</p></article></div>
  </section>
  <section className="node-operations"><div className="shell"><SectionHeader eyebrow="OPERATIONS" title="The node guide should cover the whole lifecycle." />
    <div className="operations-grid"><div><span>01</span><h3>Install</h3><p>Official binary, verification and clean data directory.</p></div><div><span>02</span><h3>Connect</h3><p>Network selection, peer discovery and P2P connectivity.</p></div><div><span>03</span><h3>Sync</h3><p>Chain synchronization, logs and progress inspection.</p></div><div><span>04</span><h3>Operate</h3><p>Restart behavior, monitoring, updates and safe shutdown.</p></div><div><span>05</span><h3>Expose</h3><p>Optional RPC/WebSocket with explicit security guidance.</p></div><div><span>06</span><h3>Upgrade</h3><p>Release hashes, compatibility notes and rollback guidance.</p></div></div>
  </div></section>
  <section className="page-section shell"><div className="infra-note"><ShieldCheck size={29}/><div><span>DECENTRALIZATION</span><h2>Official RPC is convenience. Your own node is independence.</h2><p>Rabbit can launch with official RPC and explorer endpoints while still encouraging miners, developers and infrastructure operators to run their own nodes and services.</p></div><Link to="/developers">RPC developer guide <ArrowRight size={15}/></Link></div></section>
</main>}
