import { Link } from 'react-router-dom'
import { ArrowRight, Database, Globe2, HardDrive, Network, Radio, Server, ShieldCheck, TerminalSquare } from 'lucide-react'
import SectionHeader from '../components/SectionHeader'

export default function Nodes() {
  return (
    <main>
      <section className="page-hero nodes-hero"><div className="shell page-hero-grid"><div className="page-hero-copy"><span className="hero-eyebrow"><i /> PERMISSIONLESS P2P INFRASTRUCTURE</span><h1>Run Rabbit. <em>Own your network access.</em></h1><p>Independent nodes are how wallets, developers, miners and infrastructure providers avoid depending on a single RPC operator.</p><div className="hero-ctas"><a className="button primary" href="#roles">Node roles <ArrowRight size={15} /></a><Link className="button secondary" to="/developers">RPC guide</Link></div></div><div className="node-map"><div className="node-map-head"><span>RABBIT P2P</span><b>INDEPENDENT NODES</b></div><div className="node-map-body"><div className="node-core"><img src="/rabbit-mark.png" alt="" /><strong>RABBIT</strong><small>P2P NETWORK</small></div>{['MINER','RPC','ARCHIVE','EXPLORER','APP','NODE'].map((label, i) => <span className={`node-dot n${i}`} key={label}>{label}</span>)}</div><div className="node-map-foot"><span>PEER DISCOVERY</span><span>BLOCK PROPAGATION</span><span>TX PROPAGATION</span></div></div></div></section>

      <section className="section shell" id="roles"><SectionHeader eyebrow="NODE ROLES" title="One client can serve different infrastructure goals." text="Rabbit should support independent operation instead of forcing every participant through the same hosted endpoint." /><div className="node-role-grid"><article><Network size={21} /><span>P2P</span><h3>Full node</h3><p>Join peer discovery, synchronize the chain and propagate blocks and transactions.</p></article><article><Radio size={21} /><span>ACCESS</span><h3>RPC node</h3><p>Expose controlled JSON-RPC and WebSocket access for applications or private tooling.</p></article><article><Database size={21} /><span>HISTORY</span><h3>Archive / index</h3><p>Retain deeper historical data for analytics, explorers and infrastructure services.</p></article><article><Server size={21} /><span>SERVICE</span><h3>Community infrastructure</h3><p>Operate independent RPC, indexing or explorer services without becoming a consensus administrator.</p></article></div></section>

      <section className="node-operations"><div className="shell"><SectionHeader eyebrow="OPERATOR FLOW" title="A clean path from release to independent infrastructure." /><div className="operations-grid"><div><span>01</span><HardDrive size={20} /><h3>Prepare</h3><p>Use a clean Testnet data directory and deliberately selected configuration.</p></div><div><span>02</span><TerminalSquare size={20} /><h3>Initialize</h3><p>Initialize against the finalized public Testnet genesis and network profile.</p></div><div><span>03</span><Network size={20} /><h3>Peer</h3><p>Connect to Rabbit P2P and verify independent peer discovery.</p></div><div><span>04</span><Database size={20} /><h3>Sync</h3><p>Follow canonical chain state and validate restart behavior.</p></div><div><span>05</span><Globe2 size={20} /><h3>Expose</h3><p>Optionally publish RPC with explicit access, TLS and security controls.</p></div><div><span>06</span><ShieldCheck size={20} /><h3>Maintain</h3><p>Verify releases, upgrade deliberately and retain rollback guidance.</p></div></div></div></section>

      <section className="section shell"><div className="infra-note"><ShieldCheck size={26} /><div><span>DECENTRALIZATION</span><h2>Official RPC is convenience. Your own node is independence.</h2><p>Rabbit can offer an official RPC and explorer while still encouraging miners, builders and communities to run independent infrastructure.</p></div><Link className="button secondary" to="/developers">Developer guide <ArrowRight size={14} /></Link></div></section>
    </main>
  )
}
