import { ArrowRight, Coins, Cpu, Fuel, ShieldCheck, WalletCards } from 'lucide-react'
import { Link } from 'react-router-dom'
import SectionHeader from '../components/SectionHeader'
import StatusDot from '../components/StatusDot'

export default function Rab(){return <main>
  <section className="page-hero rab-page-hero"><div className="shell page-hero-grid"><div><StatusDot tone="tech">NATIVE NETWORK ASSET</StatusDot><span className="page-kicker">RAB · RABBIT CHAIN</span><h1>The asset that powers <em>Rabbit.</em></h1><p>RAB is the native asset used by Rabbit Chain for network fees and protocol rewards. Testnet RAB exists only for testing; Mainnet economics are published with finalized production parameters.</p><div className="hero-ctas"><Link className="button primary" to="/testnet">Use Testnet <ArrowRight size={15}/></Link><Link className="button secondary" to="/lcq#rewards">Reward model</Link></div></div><div className="rab-symbol-card"><div className="rab-token"><img src="/rabbit-mark.png" alt="Rabbit Chain"/><strong>RAB</strong></div><div className="rab-symbol-grid"><div><span>NETWORK</span><b>Rabbit Chain</b></div><div><span>ROLE</span><b>Native asset</b></div><div><span>EXECUTION</span><b>EVM</b></div><div><span>CONSENSUS</span><b>LCQ</b></div></div></div></div></section>

  <section className="page-section shell"><SectionHeader eyebrow="UTILITY" title="RAB belongs to the protocol, not a marketing page." text="The site separates network utility from future market information."/><div className="rab-utility-grid"><article><Fuel/><span>GAS</span><h3>Network fees</h3><p>RAB is the native currency used by EVM transactions on Rabbit networks.</p></article><article><Cpu/><span>CONSENSUS</span><h3>Protocol rewards</h3><p>Block rewards recognize producer and committee roles according to LCQ rules.</p></article><article><WalletCards/><span>WALLET</span><h3>Native balance</h3><p>Compatible EVM wallets can display RAB after the Rabbit network is added.</p></article><article><Coins/><span>APPLICATIONS</span><h3>Onchain utility</h3><p>Rabbit applications can use the native asset for fees and network-native interactions.</p></article></div></section>

  <section className="rab-economics"><div className="shell rab-economics-grid"><div><span>CONSENSUS ECONOMICS</span><h2>70% producer.<br/><em>30% committee.</em></h2><p>The reward split is an explicit Rabbit consensus rule and is presented separately from Mainnet genesis supply or distribution.</p><Link to="/lcq#rewards">Read LCQ economics <ArrowRight size={15}/></Link></div><div className="rab-reward-visual"><div><strong>70%</strong><span>PRODUCER</span></div><div><strong>30%</strong><span>COMMITTEE</span></div></div></div></section>

  <section className="page-section shell"><SectionHeader eyebrow="TESTNET VS MAINNET" title="Do not confuse test assets with production value."/><div className="compare-network-grid"><article><span>RABBIT TESTNET</span><h3>RAB for testing</h3><ul><li>Used for Testnet gas and protocol testing</li><li>Distributed through the official faucet when live</li><li>No claim of Mainnet value</li><li>May be reset as part of Testnet operations</li></ul></article><article><span>RABBIT MAINNET</span><h3>Production RAB</h3><ul><li>Native asset of Chain ID 928</li><li>Production supply parameters published before launch</li><li>Genesis and economics must match final public artifacts</li><li>Mainnet is not live until explicit launch gates pass</li></ul></article></div></section>

  <section className="security-strip"><div className="shell security-strip-grid"><ShieldCheck size={29}/><div><span>TRANSPARENCY RULE</span><h2>No invented price, supply or exchange claims.</h2><p>Final Mainnet supply, genesis allocations and release artifacts should be published only when they are finalized and verifiable.</p></div><Link to="/mainnet">Mainnet path <ArrowRight size={15}/></Link></div></section>
</main>}
