import LegalPage from '../components/LegalPage'

const sections=[
  {id:'general',title:'General project risk',paragraphs:['Rabbit Chain is an emerging blockchain network and software project. Infrastructure, consensus behavior, tooling, documentation, application modules and operational procedures may evolve. No component should be assumed to be permanent, defect-free or guaranteed to reach a particular future state.']},
  {id:'software',title:'Technical and software risk',paragraphs:['Nodes, wallets, explorers, RPC services, miners, smart contracts and web applications may contain bugs, vulnerabilities, incompatibilities or unexpected behavior. Upgrades and configuration changes can cause service interruption or data inconsistency.'],items:['Transactions may fail or behave differently from what a user expects.','Explorer or indexed data may lag behind canonical network state.','RPC endpoints may return errors, become congested or become unavailable.','Software defects may result in partial or total loss of digital assets.']},
  {id:'wallet',title:'Wallet and key-management risk',paragraphs:['You are solely responsible for your private keys, seed phrases, signing devices and wallet software. Rabbit Chain does not have the ability to reverse transactions or restore a lost private key.'],items:['Lost keys can make assets permanently inaccessible.','Compromised wallets may result in theft.','Malicious approvals or signatures may cause irreversible loss.','Fake websites, wallet prompts and social-engineering attacks may impersonate Rabbit Chain.']},
  {id:'consensus',title:'Mining, LCQ and network-participation risk',paragraphs:[
    'Rabbit Chain uses LCQ Consensus to coordinate eligible participants and block production. Permissionless participation does not remove operational or protocol risk.',
    'Eligibility, queue position, fallback behavior, committee participation, connectivity, hardware performance, network conditions and future protocol upgrades can affect participation. There is no guarantee that mining or operating infrastructure will be profitable or result in any specific reward.'
  ]},
  {id:'testnet',title:'Testnet and Mainnet transition risk',paragraphs:[
    'Rabbit Testnet, Chain ID 9280, is the first public launch environment. Testnet state, balances, assets, endpoints and software may be reset, changed or retired during validation.',
    'Rabbit Mainnet, Chain ID 928, is a separate production network planned to follow successful validation and launch gates. Testnet participation does not guarantee Mainnet allocations, balances, rewards, access or economic rights unless explicitly stated in a future official specification.'
  ]},
  {id:'contracts',title:'Smart-contract and Platform risk',paragraphs:[
    'If Rabbit Platform modules such as Swap, Liquidity, Launchpool, Token Factory or Bridge are activated, they may introduce smart-contract, liquidity, integration, oracle, accounting and user-interface risks.',
    'A module displayed as planned, preview or coming soon should not be interpreted as audited, deployed or available. Users should independently verify contract addresses and official release information before interacting.'
  ]},
  {id:'market',title:'Market, liquidity and asset risk',paragraphs:['Digital assets can be highly volatile and may lose some or all of their value. Markets may be illiquid, fragmented or unavailable. Nothing on Rabbit Chain guarantees price support, exchange listing, liquidity, demand or an exit opportunity. Testnet assets should not be treated as having guaranteed monetary value.']},
  {id:'infra',title:'Infrastructure and availability risk',paragraphs:['Official website, DNS, RPC, WebSocket, explorer, faucet and download infrastructure may become unavailable, degraded, rate-limited or inaccurate because of maintenance, hosting failure, attacks, congestion or network problems. Users should be able to verify releases and, where appropriate, operate independent infrastructure.']},
  {id:'thirdparty',title:'Third-party risk',paragraphs:['Wallets, exchanges, bridges, hosting providers, analytics systems, community tools and applications not operated by Rabbit Chain may fail, be compromised, change terms or provide incorrect information. Their inclusion in an ecosystem does not create a guarantee or warranty by Rabbit Chain.']},
  {id:'legal',title:'Legal and regulatory risk',paragraphs:['Rules governing blockchain software, mining, digital assets, smart contracts, tokens and DeFi vary and can change rapidly. Activities allowed in one jurisdiction may be regulated or prohibited in another. Users are responsible for understanding obligations that apply to them.']},
  {id:'advice',title:'No advice, guarantee or promise',paragraphs:['Nothing on the Rabbit Chain website, Whitepaper, documentation, GitHub, explorer, social accounts, network interfaces or community channels should be interpreted as financial, investment, legal or tax advice, or as a guarantee of profit, price, listing, liquidity, technical stability, launch timing, future development or adoption.']},
  {id:'contact',title:'Verify official information',paragraphs:['Use rabbitchain.org, github.com/rabbitmainnet and x.com/rabbit_mainnet as official reference points. Verify domains, software hashes, network identifiers and contract addresses before acting.']}
]

export default function RiskDisclosure(){return <LegalPage eyebrow="LEGAL · RISK" title="Risk Disclosure" intro="Key technical, network, wallet, economic and legal risks associated with using Rabbit Chain and related services." sections={sections}/>}
