import { ArrowRight, CheckCircle2, Code2, Copy, Cpu, FlaskConical, Globe2, Network, Radio, ShieldCheck, Wallet } from 'lucide-react'
import SectionHeader from '../components/SectionHeader'
import StatusDot from '../components/StatusDot'
import CopyButton from '../components/CopyButton'
import { NETWORKS } from '../config/networks'

export default function Testnet({ walletState, onConnect, onSwitch }){
  const n=NETWORKS.testnet
  return <main>
    <section className="page-hero testnet-page-hero"><div className="shell page-hero-grid"><div><StatusDot tone="launch">FIRST PUBLIC LAUNCH</StatusDot><span className="page-kicker">RABBIT TESTNET · CHAIN ID 9280</span><h1>Use Rabbit before <em>Mainnet.</em></h1><p>The public Testnet is where miners, node operators, wallets and developers validate the Rabbit network in the open.</p><div className="hero-ctas"><button className="button primary" onClick={onConnect}><Wallet size={16}/>{walletState.account?'Open wallet':'Connect wallet'}</button><button className="button secondary" onClick={()=>onSwitch(n)} disabled={!n.publicRpcReady}>Add Testnet</button></div></div><div className="network-detail-card"><div className="network-detail-top"><img src="/rabbit-mark.png" alt=""/><div><span>RABBIT TESTNET</span><b>PUBLIC NETWORK TRACK</b></div><StatusDot tone="launch">PRE-LAUNCH</StatusDot></div><div className="network-detail-grid"><div><span>CHAIN ID</span><strong>9280</strong></div><div><span>HEX</span><strong>0x2440</strong></div><div><span>CONSENSUS</span><strong>LCQ</strong></div><div><span>EXECUTION</span><strong>EVM</strong></div><div><span>ASSET</span><strong>RAB</strong></div><div><span>TEST ASSET</span><strong>RUSD</strong></div></div></div></div></section>

    <section className="page-section shell" id="wallet"><SectionHeader eyebrow="QUICK START" title="Everything needed to enter Testnet." text="The Rabbit portal keeps the common first steps in one place so users do not have to hunt through social posts or old documentation." />
      <div className="quick-start-grid"><article><Wallet/><span>01</span><h3>Connect wallet</h3><p>Connect an installed EVM-compatible wallet. Connection does not sign a transaction.</p><button onClick={onConnect}>Connect wallet <ArrowRight size={14}/></button></article><article><FlaskConical/><span>02</span><h3>Get RAB / RUSD</h3><p>Test assets will be distributed through the official faucet when public Testnet opens.</p><button disabled>Faucet at launch</button></article><article><Globe2/><span>03</span><h3>Open explorer</h3><p>Inspect blocks, transactions, addresses and contracts through the official explorer.</p><button disabled>Explorer reserved</button></article><article><Cpu/><span>04</span><h3>Start mining</h3><p>Download the official Rabbit client, verify the release and participate through LCQ.</p><a href="/mining">Mining guide <ArrowRight size={14}/></a></article></div>
    </section>

    <section className="endpoint-section"><div className="shell"><SectionHeader eyebrow="NETWORK CONNECTION" title="Official Testnet endpoints." text="The domains are reserved in the site configuration, but actions stay disabled until the public services are actually online." />
      <div className="endpoint-table"><div className="endpoint-row"><span><Radio size={16}/>JSON-RPC</span><code>{n.rpcUrl}</code><em>RESERVED</em><CopyButton value={n.rpcUrl}/></div><div className="endpoint-row"><span><Network size={16}/>WebSocket</span><code>{n.wsUrl}</code><em>RESERVED</em><CopyButton value={n.wsUrl}/></div><div className="endpoint-row"><span><Globe2 size={16}/>Explorer</span><code>{n.explorerUrl}</code><em>RESERVED</em><CopyButton value={n.explorerUrl}/></div><div className="endpoint-row"><span><FlaskConical size={16}/>Faucet</span><code>{n.faucetUrl}</code><em>RESERVED</em><CopyButton value={n.faucetUrl}/></div></div>
    </div></section>

    <section className="page-section shell"><SectionHeader eyebrow="WHO SHOULD TEST" title="Public validation has four tracks." text="Rabbit Testnet is not just for app developers. It validates the complete network surface before Mainnet." />
      <div className="validation-grid"><article><Cpu/><h3>Miners</h3><p>Producer eligibility, work submission, queue behavior, rewards and recovery.</p><a href="/mining">Mining path →</a></article><article><Network/><h3>Node operators</h3><p>P2P discovery, synchronization, restart behavior, RPC and independent infrastructure.</p><a href="/nodes">Node path →</a></article><article><Wallet/><h3>Wallets & users</h3><p>Chain addition, switching, balances, transfers and explorer visibility.</p><button onClick={onConnect}>Connect wallet →</button></article><article><Code2/><h3>Developers</h3><p>EVM contracts, JSON-RPC, transaction workflows and tooling compatibility.</p><a href="/developers">Developer path →</a></article></div>
    </section>

    <section className="safety-section"><div className="shell safety-grid"><div><ShieldCheck size={30}/><span>TESTNET SAFETY</span><h2>Test assets are not Mainnet assets.</h2></div><div><p>Rabbit Testnet RAB and RUSD are for testing only. The official site will never ask for a seed phrase or private key. Verify downloads and endpoints from the Rabbit GitHub and this domain.</p><div className="safety-points"><span><CheckCircle2 size={15}/>No seed phrase requested</span><span><CheckCircle2 size={15}/>No Mainnet value on faucet</span><span><CheckCircle2 size={15}/>RPC activation shown explicitly</span></div></div></div></section>
  </main>
}
